### ISSUE TITLE
Check results appear on the wrong workflow

### ISSUE THREAD

**Issue by zirkelc** [wearerequired/lint-action#577] opened 2023-01-15 18:04 UTC
I noticed that the check result from my `lint.yml` workflow appear on another workflow file, in this case `unit-tests.yml`:

![2023-01-15_18-59-38](https://user-images.githubusercontent.com/950244/212558606-ffe50e47-df66-486c-ab16-27b971296aec.jpg)

![2023-01-15_19-02-11](https://user-images.githubusercontent.com/950244/212558657-55e2dc53-0b6c-43ed-922c-5d628851c21c.jpg)

I expected the results to appear as **Lint / ESLint** and **Lint / TypeScript**. Somehow, when the check run is being created it picks the wrong workflow run?

**Comment by ocean90** [comment] 2023-01-19 08:10
Hi there, this is an issue with how the GitHub checks API works. Checks are attached to commit SHAs and the annotations are added to latest workflow run for the commit being tested. This is nothing this action can fix.

Duplicate of #401, #280, #97, #93.

**Closed by ocean90** 2023-01-19 08:10 UTC
Labels: duplicate
