### ISSUE TITLE
Lint tasks are getting added under wrong workflow

### ISSUE THREAD

**Issue by cseas** [wearerequired/lint-action#401] opened 2022-02-24 08:30 UTC
Opening #35 again because I'm experiencing the same behaviour.

`lint-action` is added under my `ci` workflow but the ESLint and Prettier checks are getting added under a different workflow that I have.

<img width="324" alt="Screenshot 2022-02-24 at 1 59 44 PM" src="https://user-images.githubusercontent.com/29686866/155487424-5df2f7a2-49d9-4828-9816-c4310756b332.png">

Does `lint-action` add all new checks to the first workflow by default?

**Comment by cseas** [comment] 2022-02-24 08:50
Had to work around the problem by creating a separate workflow file for this action. But that seems redundant since now I need to setup and install node modules in two different workflows. Earlier one workflow was enough to do all CI related checks.

<img width="332" alt="Screenshot 2022-02-24 at 2 18 59 PM" src="https://user-images.githubusercontent.com/29686866/155490599-423c4368-868f-4e23-9498-9e62669472be.png">

**Comment by cseas** [comment] 2022-02-24 09:13
Doesn't look like even that fixed it. The action is definitely adding new checks to the first workflow, whichever one it is. Another gave this result:

<img width="332" alt="Screenshot 2022-02-24 at 2 18 59 PM" src="https://user-images.githubusercontent.com/29686866/155494454-4e19126e-b1b0-4bf9-83c0-a4d9012364c6.png">

**Comment by ocean90** [comment] 2022-03-08 08:01
Hi there, this is an issue with how the GitHub checks API works. Checks are attached to commit SHAs and the annotations are added to latest workflow run for the commit being tested. This is nothing this action can fix.

Related report: https://github.community/t/github-actions-status-checks-created-on-incorrect-check-suite-id/16685

Duplicate of #280, #97, #93.

**Closed by ocean90** 2022-03-08 08:01 UTC
Labels: duplicate
