### ISSUE TITLE
Linter result gets attached to the wrong workflow

### ISSUE THREAD

**Issue by andreiz** [wearerequired/lint-action#657] opened 2023-06-08 17:12 UTC
I have 2 workflows running concurrently, build-and-test one and a linter one (using Apple's swift-format). The linter result (named `swift-format`) is being attached either to the linter workflow or to the build-and-test workflow,  seemingly randomly.

This is how I expect it's supposed to be where the `swift-format` result is attached to my linter workflow job list.

<img width="324" alt="Screenshot 2023-06-08 at 10 09 48" src="https://github.com/wearerequired/lint-action/assets/40809/46b7d624-53fb-4f04-9968-5f98b7c05f10">

And this linter run does not have the result attached:

<img width="289" alt="Screenshot 2023-06-08 at 10 09 06" src="https://github.com/wearerequired/lint-action/assets/40809/8a44c96c-779a-4beb-9652-847a0a586efb">

But instead it ends up in the build-and-test workflow:

<img width="329" alt="Screenshot 2023-06-08 at 10 07 02" src="https://github.com/wearerequired/lint-action/assets/40809/cb060dad-452d-4bc6-95c3-6a4df48d8c06">

Can you think of why this might be happening?

**Comment by ocean90** [comment] 2023-06-15 19:57
Hi there, this is an issue with how the GitHub checks API works. Checks are attached to commit SHAs and the annotations are added to latest workflow run for the commit being tested. This is nothing this action can fix.

Duplicate of #577, #401, #280, #97, #93.

**Closed by ocean90** 2023-06-15 19:57 UTC
Labels: duplicate
