### ISSUE TITLE
disable option for Unchanged files with check annotations

### ISSUE THREAD

**Issue by viratvasu** [wearerequired/lint-action#475] opened 2022-05-31 05:54 UTC
- Is there any option or way to disable this
- I just want to apply lint only on files that are modifies in PR
![Screenshot (494)](https://user-images.githubusercontent.com/36135781/171102200-d0a7fd18-d841-483d-af88-0e4717d5bf06.png)

**Comment by ocean90** [comment] 2022-06-10 07:58
This is a duplicate of #389 and #47.

**Closed by ocean90** 2022-06-10 07:58 UTC
Labels: duplicate
