### ISSUE TITLE
Running eslint against only changed files

### ISSUE THREAD

**Issue by davidwilde** [wearerequired/lint-action#156] opened 2021-02-05 11:30 UTC
Hi there,

I'm looking to integrate this into my company's workflow but we have already got quite far down the road without good linting and this is something that we would like to change over time. However when I use this, I get all the lint errors and not just the ones from the Pull request. I couldn't see any option to do this, but I believe I could write one.

Before I go ahead and write one and make a PR, I'd just like to make sure that this is something you would be happy with as it will take up quite a bit of my time.

Thanks

**Comment by ocean90** [comment] 2021-02-05 11:44
Hi David, thank you for your interest in working on the action. Though, this request is a duplicate of #47. Please check out the comments there and the related PR #46 which probably needs a new owner.

**Closed** 2021-02-07 14:14 UTC
Labels: duplicate
